apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    artifact.spinnaker.io/location: gha-runner-scale-set
    artifact.spinnaker.io/name: amd-standard-gha-rs-no-permission
    artifact.spinnaker.io/type: kubernetes/serviceAccount
    artifact.spinnaker.io/version: ""
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"artifact.spinnaker.io/location":"gha-runner-scale-set","artifact.spinnaker.io/name":"amd-standard-gha-rs-no-permission","artifact.spinnaker.io/type":"kubernetes/serviceAccount","artifact.spinnaker.io/version":"","moniker.spinnaker.io/application":"gha-runner-scale-set","moniker.spinnaker.io/cluster":"serviceAccount amd-standard-gha-rs-no-permission"},"finalizers":["actions.github.com/cleanup-protection"],"labels":{"actions.github.com/scale-set-name":"amd-standard","actions.github.com/scale-set-namespace":"gha-runner-scale-set","app.kubernetes.io/instance":"amd-standard","app.kubernetes.io/managed-by":"spinnaker","app.kubernetes.io/name":"amd-standard","app.kubernetes.io/part-of":"gha-rs","app.kubernetes.io/version":"0.8.3","helm.sh/chart":"gha-rs-0.8.3","k8s.hulu.com/ingested-by-spinnaker":"true","k8s.hulu.com/mariner-app":"gha-runner-scale-set"},"name":"amd-standard-gha-rs-no-permission","namespace":"gha-runner-scale-set"}}
    moniker.spinnaker.io/application: gha-runner-scale-set
    moniker.spinnaker.io/cluster: serviceAccount amd-standard-gha-rs-no-permission
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: amd-standard
    actions.github.com/scale-set-namespace: gha-runner-scale-set
    app.kubernetes.io/instance: amd-standard
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: amd-standard
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.8.3
    helm.sh/chart: gha-rs-0.8.3
    k8s.hulu.com/mariner-app: gha-runner-scale-set
  name: amd-standard-gha-rs-no-permission
  namespace: gha-runner-scale-set
