apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    artifact.spinnaker.io/location: ""
    artifact.spinnaker.io/name: argo-workflow-br-argo-workflows-view
    artifact.spinnaker.io/type: kubernetes/clusterRole
    artifact.spinnaker.io/version: ""
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{"artifact.spinnaker.io/location":"","artifact.spinnaker.io/name":"argo-workflow-br-argo-workflows-view","artifact.spinnaker.io/type":"kubernetes/clusterRole","artifact.spinnaker.io/version":"","moniker.spinnaker.io/application":"argo-p2fs-test","moniker.spinnaker.io/cluster":"clusterRole argo-workflow-br-argo-workflows-view"},"labels":{"app.kubernetes.io/component":"workflow-controller","app.kubernetes.io/instance":"argo-workflow-br","app.kubernetes.io/managed-by":"spinnaker","app.kubernetes.io/name":"argo-workflows-workflow-controller","app.kubernetes.io/part-of":"argo-workflows","helm.sh/chart":"argo-workflows-0.40.7","k8s.hulu.com/ingested-by-spinnaker":"true","k8s.hulu.com/mariner-app":"argo-p2fs-test","rbac.authorization.k8s.io/aggregate-to-view":"true"},"name":"argo-workflow-br-argo-workflows-view"},"rules":[{"apiGroups":["argoproj.io"],"resources":["workflows","workflows/finalizers","workfloweventbindings","workfloweventbindings/finalizers","workflowtemplates","workflowtemplates/finalizers","cronworkflows","cronworkflows/finalizers","clusterworkflowtemplates","clusterworkflowtemplates/finalizers","workflowtasksets","workflowtasksets/finalizers","workflowtaskresults","workflowtaskresults/finalizers","workflowartifactgctasks","workflowartifactgctasks/finalizers"],"verbs":["get","list","watch"]}]}
    moniker.spinnaker.io/application: argo-p2fs-test
    moniker.spinnaker.io/cluster: clusterRole argo-workflow-br-argo-workflows-view
  creationTimestamp: "2024-01-17T19:43:34Z"
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflow-br
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: argo-workflows-workflow-controller
    app.kubernetes.io/part-of: argo-workflows
    helm.sh/chart: argo-workflows-0.40.7
    k8s.hulu.com/mariner-app: argo-p2fs-test
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: argo-workflow-br-argo-workflows-view
  resourceVersion: "97888416"
  uid: 73f82704-6e1e-450e-aa28-306237746dfe
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workfloweventbindings
  - workfloweventbindings/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  - workflowtasksets
  - workflowtasksets/finalizers
  - workflowtaskresults
  - workflowtaskresults/finalizers
  - workflowartifactgctasks
  - workflowartifactgctasks/finalizers
  verbs:
  - get
  - list
  - watch
